name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - '.github/workflows/**'

env:
  IMAGE_NAME: "simaofsilva/renovatebot-docker-renovate"
  REPO_URL: "https://github.com/renovatebot/docker-renovate"
  LOCAL_PATH: "/tmp/docker-renovate"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read Dockerfile
        id: dockerfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Dockerfile

      - name: Get version for tag
        id: version
        shell: bash
        run: |
          echo "${{ steps.dockerfile.outputs.content }}" > /tmp/content.txt
          echo "::set-output name=VERSION::$(sed -n '2p' /tmp/content.txt | sed 's|ARG RENOVATE_VERSION=||1')"

      - name: Print version
        run: |
          echo ${{ steps.version-tag.outputs.VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone original repository
        run: |
          git clone ${{ env.REPO_URL }} ${{ env.LOCAL_PATH }}

      - name: Check if custom Dockerfile is been used
        run: |
          cp Dockerfile ${{ env.LOCAL_PATH }}
          cat ${{ env.LOCAL_PATH }}/Dockerfile

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.LOCAL_PATH }}
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}-slim
            ${{ env.IMAGE_NAME }}:slim
            ${{ env.IMAGE_NAME }}:latest
